info:
  title: Digital Waste Tracking Receipt API
  version: '1.0'
  description: API for managing waste movements and receipts
openapi: 3.0.0
servers:
  - url: http://0.0.0.0:3001
components:
  schemas:
    form:
      type: string
      enum:
        - Gas
        - Liquid
        - Solid
        - Powder
        - Sludge
        - Mixed
    Quantity:
      type: object
      properties:
        value:
          type: number
        unit:
          type: string
        isEstimate:
          type: boolean
      required:
        - value
        - unit
        - isEstimate
    Waste:
      type: object
      properties:
        ewcCode:
          type: string
        description:
          type: string
        form:
          $ref: '#/components/schemas/form'
        containers:
          type: string
        quantity:
          $ref: '#/components/schemas/Quantity'
      required:
        - ewcCode
        - description
        - form
        - containers
        - quantity
    waste:
      type: array
      items:
        $ref: '#/components/schemas/Waste'
    meansOfTransport:
      type: string
      enum:
        - Road
        - Rail
        - Air
        - Sea
        - Waterway
        - Other
    Carrier:
      type: object
      properties:
        registrationNumber:
          type: string
        organisationName:
          type: string
        address:
          type: string
        emailAddress:
          type: string
          x-format:
            email: true
        companiesHouseNumber:
          type: string
        phoneNumber:
          type: string
        vehicleRegistration:
          type: string
        meansOfTransport:
          $ref: '#/components/schemas/meansOfTransport'
      required:
        - registrationNumber
        - organisationName
        - address
        - emailAddress
        - phoneNumber
        - vehicleRegistration
        - meansOfTransport
    Acceptance:
      type: object
      properties:
        acceptingAll:
          type: boolean
        quantityNotAccepted:
          type: string
        rejectionReason:
          type: string
      required:
        - acceptingAll
        - quantityNotAccepted
        - rejectionReason
    Receiver:
      type: object
      properties:
        authorisationType:
          type: string
        authorisationNumber:
          type: string
        regulatoryPositionStatement:
          type: string
      required:
        - authorisationType
        - authorisationNumber
    estimateOrActual:
      type: string
      enum:
        - Estimate
        - Actual
    disposalOrRecoveryCode:
      type: object
      properties:
        code:
          type: string
        quantity:
          $ref: '#/components/schemas/Quantity'
    Receipt:
      type: object
      properties:
        estimateOrActual:
          $ref: '#/components/schemas/estimateOrActual'
        dateTimeReceived:
          type: string
          format: date-time
        disposalOrRecoveryCode:
          $ref: '#/components/schemas/disposalOrRecoveryCode'
      required:
        - estimateOrActual
        - dateTimeReceived
    Movement:
      type: object
      properties:
        receivingSiteId:
          type: string
        receiverReference:
          type: string
        specialHandlingRequirements:
          type: string
        waste:
          $ref: '#/components/schemas/waste'
        carrier:
          $ref: '#/components/schemas/Carrier'
        acceptance:
          $ref: '#/components/schemas/Acceptance'
        receiver:
          $ref: '#/components/schemas/Receiver'
        receipt:
          $ref: '#/components/schemas/Receipt'
      required:
        - receivingSiteId
        - receiverReference
        - carrier
        - acceptance
        - receiver
        - receipt
    ReceiptMovement:
      type: object
      properties:
        movement:
          $ref: '#/components/schemas/Movement'
      required:
        - movement
    Model1:
      type: object
      properties:
        carrierMovementId:
          type: string
          description: An identifier of the movement, unique for the carrier only. This field will only be returned if the carrier is known to the service and should be provided to the carrier by the receiver.
        globalMovementId:
          type: string
          description: Globally unique identifier of the movement. This id should be stored and used for any subsequent updates of the movement.
          x-format:
            guid: true
    BadRequestResponse:
      type: object
      properties:
        statusCode:
          type: number
          enum:
            - 400
        error:
          type: string
        message:
          type: string
    Model2:
      type: object
      properties:
        message:
          type: string
          description: Success message
    NotFoundResponse:
      type: object
      properties:
        statusCode:
          type: number
          enum:
            - 404
        error:
          type: string
        message:
          type: string
    HazardousComponent:
      type: object
      properties:
        component:
          type: string
        concentration:
          type: number
        hazCode:
          type: string
      required:
        - component
        - concentration
        - hazCode
    components:
      type: array
      items:
        $ref: '#/components/schemas/HazardousComponent'
    HazardousWaste:
      type: object
      properties:
        isHazerdousWaste:
          type: boolean
        components:
          $ref: '#/components/schemas/components'
      required:
        - isHazerdousWaste
        - components
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Success message
    400Response:
      type: object
      properties:
        statusCode:
          type: number
          enum:
            - 400
        error:
          type: string
        message:
          type: string
    404Response:
      type: object
      properties:
        statusCode:
          type: number
          enum:
            - 404
        error:
          type: string
        message:
          type: string
tags: []
paths:
  /movements/receive:
    post:
      summary: Endpoint to be used when waste is received but the carrier has not already recorded the waste movement so has no id.
      operationId: postMovementsReceive
      tags:
        - movements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceiptMovement'
      responses:
        '200':
          description: The waste movement has been stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
  /movements/{wasteTrackingId}/receive:
    put:
      summary: Endpoint to be used when waste is received and the carrier has a waste tracking id.
      operationId: putMovementsWastetrackingidReceive
      parameters:
        - name: wasteTrackingId
          in: path
          schema:
            type: string
            description: The globally unique id of the movement.
            x-format:
              guid: true
          description: The globally unique id of the movement.
          required: true
      tags:
        - movements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceiptMovement'
      responses:
        '200':
          description: The waste movement receipt has been processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model2'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '404':
          description: Movement not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /movements/{wasteTrackingId}/receive/hazardous:
    put:
      summary: Endpoint used to provide hazardous waste details for a waste movement
      operationId: putMovementsWastetrackingidReceiveHazardous
      parameters:
        - name: wasteTrackingId
          in: path
          schema:
            type: string
          required: true
      tags:
        - movements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HazardousWaste'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400Response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Response'
